name: Production Release & Deploy

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - '.gitignore'
      - '.husky/**'
      - '.prettierrc'
      - 'eslint.config.js'
      - 'LICENSE'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  issues: write
  pull-requests: write

concurrency:
  group: "pages-main"
  cancel-in-progress: true

jobs:
  audit-and-release:
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.semantic.outputs.new_release_published }}
      version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test:run

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy:
    needs: audit-and-release
    if: needs.audit-and-release.outputs.published == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: v${{ needs.audit-and-release.outputs.version }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_APP_VERSION: v${{ needs.audit-and-release.outputs.version }}

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Upload artifact for GH Pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5